apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-applicationset-json-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  token: "${{ include "argocd-applicationset-json-plugin.fullname" . }}:token"
  baseUrl: "http://{{ include "argocd-applicationset-json-plugin.fullname" . }}.argocd.svc.cluster.local"
  requestTimeout: "30"
